print("Hello!...")
print(format('iii',' >16'))
print(format('_III_',' >17')) 
print(format('|     |',' >18')) 
print(format('_|_____|_',' >19')) 
print(format('|  HAPPY  |',' >20'))
print(format('_|_________|_',' >21')) 
print(format('|  BIRTHDAY   |',' >22')) 
print(format('_|_____________|_','>23')) 
print(format('|    SRAVANTHI    |',' >24')) 
print(format('_|_________________|_',' >25'))
print('A Message loading.........')
print(' Dear sravanthi,')
print("\tCount your age by friends, not years. Count your life by smiles, not tears. ")
print('\tMay you have a wonderful year full of love and joy.')
print('\t Once again happy birthday to my lovely friend.')
print('\t\t\t\t\t\t\t From')
print('\t\t\t\t\t\t\t KEERTHIKA')
